apiVersion: v1
kind: ConfigMap
metadata:
  name: cerk-generator-configs
data:
  init.json: |
    {
      "scheduler": "THREADING_SCHEDULER",
      "router": "ROUTER_BROADCAST",
      "config_loader": "CONFIG_LOADER_FILE",
      "ports": {
        "mqtt-generator": "PORT_MQTT_MOSQUITTO",
        "sequence-generator": "PORT_SEQUENCE_GENERATOR",
        "health": "PORT_HEALTH_CHECK_HTTP"
      }
    }
  config.json: |
    {
      "routing_rules": [
        "mqtt-generator"
      ],
      "ports": {
        "mqtt-generator": {
          "host": "tcp://mosquitto:1883",
          "send_topic": "input"
        },
        "sequence-generator": {
          "delivery_guarantee": 2
        },
        "health": {
          "ports_to_check": []
        }
      }
    }
