version: '3.7'

services:
  test:
    image: lazzaretti/docker-rust-cerk:0.3.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: >
      /bin/bash -c "
      cargo test --all
      && rustup component add rustfmt
      && cargo fmt -- --check
      "
  doc:
    image: lazzaretti/docker-rust-cerk:0.3.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: cargo doc --all
  check-readme:
    image: lazzaretti/ce-rust-docker-cargo-readme:3.1.2
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: 
      - /bin/bash 
      - -c
      - |
        diff <(cargo readme  -r cerk) cerk/README.md || (echo 1>&2 'Please update the cerk/README with `cargo readme -r cerk > cerk/README.md`' && exit 1 )
