version: '3.7'

services:
  test:
    image: lazzaretti/docker-rust-cerk:0.4.0
    volumes:
      - .:/cerk/
      - ./lib/libmosquitto.so.1:/usr/local/lib/libmosquitto.so
      - ./lib/libmosquitto.so.1:/usr/lib/libmosquitto.so.1
    working_dir: /cerk
    command: >
      /bin/bash -c "
      cargo test --all
      && rustup component add rustfmt
      && cargo fmt -- --check
      "
  doc:
    image: lazzaretti/docker-rust-cerk:0.4.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: cargo doc --all
  check-readme:
    image: lazzaretti/ce-rust-docker-cargo-readme:3.1.2
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: ./check-readme.sh
