version: '3.7'

services:
  test:
    image: ghcr.io/ce-rust/rust-cerk:v0.8.0
    volumes:
      - .:/cerk/
      - ./lib/libmosquitto.so.1:/usr/local/lib/libmosquitto.so
      - ./lib/libmosquitto.so.1:/usr/lib/libmosquitto.so.1
    working_dir: /cerk
    command: >
      /bin/bash -c "
      cargo test --all
      && rustup component add rustfmt
      && cargo fmt -- --check
      "
  doc:
    image: ghcr.io/ce-rust/rust-cerk:v0.8.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: cargo doc --all
  check-readme:
    image: ghcr.io/ce-rust/cargo-readme:v3.3.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: ./check-readme.sh
  deny:
    image: ghcr.io/ce-rust/rust-cerk:v0.8.0
    volumes:
      - .:/cerk/
    working_dir: /cerk
    command: >
      /bin/bash -c "
      cargo install cargo-deny
      && cargo deny check
      "
