version: '3.7'

services:
  cerk-router:
    build: 
      context: ../../../
      dockerfile: Dockerfile.example.mqtt
    volumes:
      - ../../../:/cerk/
    working_dir: /cerk
    command: cargo run --bin mqtt
  mqtt-broker:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001
