version: '3.7'

services:
  hello-world:
    image: rust:1.38
    volumes:
      - ../../../:/cerk/
    working_dir: /cerk
    command: cargo run --bin mqtt
  mqtt_broker:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001
