version: '3.7'

services:
  cerk-publisher:
    image: lazzaretti/docker-rust-cerk:0.3.0
    environment: 
      - RUST_BACKTRACE=1
    volumes:
      - ../../../:/cerk/
    working_dir: /cerk
    command: cargo run --bin sequence_to_mqtt
    depends_on: 
      - mqtt-broker
    links: 
      - mqtt-broker
  cerk-subscriber:
    image: lazzaretti/docker-rust-cerk:0.3.0
    volumes:
      - ../../../:/cerk/
    working_dir: /cerk
    command: cargo run --bin mqtt-to-printer
    depends_on: 
      - mqtt-broker
    links: 
      - mqtt-broker
  mqtt-broker:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001
  mqtt-client:
    image: eclipse-mosquitto
    command: mosquitto_sub -h "mqtt-broker" -t test