version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  cerk-amqp:
    image: ghcr.io/ce-rust/rust-cerk:v0.8.0
    volumes:
      - ../../:/cerk/
    working_dir: /cerk/integration-tests/reliable-amqp/cerk-amqp
    command: cargo run
    environment:
      - "AMQP_BROKER_URL=amqp://rabbitmq:5672/%2f"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  test-executor:
    image: ghcr.io/ce-rust/rust-cerk:v0.8.0
    volumes:
      - ../../:/cerk/
    working_dir: /cerk/integration-tests/reliable-amqp/test-executor
    command: cargo test -- --test-threads 1 --nocapture # have side effects -> run in sequentially
    environment:
      - "AMQP_BROKER_URL=amqp://rabbitmq:5672/%2f"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
