version: '3.7'

services:
  router:
    build:
      context: ../../
      dockerfile: integration-tests/mqtt/mqtt/Dockerfile
  mqtt-broker:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001
  mqtt-client:
    image: eclipse-mosquitto
    command: mosquitto_sub -h "mqtt-broker" -t test