version: '3.7'

services:
  limited:
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./mosquitto_limited.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
  unlimited:
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./mosquitto_unlimited.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1884:1883
  cerk:
    image: lazzaretti/docker-rust-cerk:0.3.0
    environment:
      - MOSQUITTO_GIT_URL=https://github.com/ce-rust/mosquitto
      - MOSQUITTO_GIT_HASH=9f834dff9095e6731937d5eac767dbaca46491ac
    volumes:
      - ../../:/cerk/
    working_dir: /cerk/integration-tests/reliable-mqtt/cerk-mqtt
    command: cargo run
    depends_on:
      - limited
      - unlimited
    links:
      - limited
      - unlimited
  test-executor:
    image: lazzaretti/docker-rust-cerk:0.3.0
    volumes:
      - ../../:/cerk/
    working_dir: /cerk/integration-tests/reliable-mqtt/test-executor
    command: cargo test -- --test-threads 1 --nocapture # have side effects -> run them sequentially
    depends_on:
      - limited
      - unlimited
    links:
      - limited
      - unlimited
