apiVersion: v1
kind: ConfigMap
metadata:
  name: cerk-generator-configs
data:
  init.json: |
    {
      "scheduler": "THREADING_SCHEDULER",
      "router": "ROUTER_BROADCAST",
      "config_loader": "CONFIG_LOADER_FILE",
      "ports": {
        "ampq": "PORT_AMQP",
        "sequence-generator": "PORT_SEQUENCE_GENERATOR",
        "health": "PORT_HEALTH_CHECK_HTTP"
      }
    }
  config.json: |
    {
      "routing_rules": [
        "ampq"
      ],
      "ports": {
        "ampq": {
          "uri": "amqp://rabbitmq:5672/%2f",
          "publish_channels": [
            {
              "name": "input",
              "ensure_exchange": true
            }
          ]
        },
        "sequence-generator": {
          "delivery_guarantee": 2
        },
        "health": {
          "ports_to_check": ["ampq"]
        }
      }
    }
