[package]
name = "cerk_examples"
version = "0.1.0"
authors = [
    "Linus Basig <linus@basig.me>",
    "Fabrizio Lazzaretti <fabrizio@lazzaretti.me>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cerk = { path = "../cerk" }
cerk_runtime_threading = { path = "../cerk_runtime_threading" }
cerk_router_broadcast = { path = "../cerk_router_broadcast" }
cerk_config_loader_static = { path = "../cerk_config_loader_static" }
