version: '3.7'

services:
  archlinux:
    build: archlinux
    volumes: 
      - ..:/cerk/
      - ../lib/libmosquitto.so.1:/usr/local/lib/libmosquitto.so
      - ../lib/libmosquitto.so.1:/usr/lib/libmosquitto.so.1
  ubuntulinux:
    build: ubuntulinux
    volumes: 
      - ..:/cerk/
      - target:/cerk/target/ # dont use target from host
      - ../lib/libmosquitto.so.1:/usr/local/lib/libmosquitto.so
      - ../lib/libmosquitto.so.1:/usr/lib/libmosquitto.so.1

volumes:
  target: {}