version: '3.7'

services:
  archlinux:
    build: archlinux
    volumes: 
      - ..:/cerk/
      - targeta:/cerk/target/ # dont use target from host
  ubuntulinux:
    build: ubuntulinux
    volumes: 
      - ..:/cerk/
      - targetu:/cerk/target/ # dont use target from host

volumes:
  targeta: { }
  targetu: { }
