name: Verify

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  check-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run deny docker compose
        run: docker-compose run --rm deny



